version: "3.10"

services:
  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    image: frontend:latest
    ports:
      - 8501:8501
    networks:
      - project_network
    depends_on:
      - backend
    volumes:
      - ./Frontend:/app/backend


  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    image: backend:latest
    ports:
      - 8080:8080
    networks:
      - project_network
networks:
  project_network: